name: Deploy Spring Boot to AWS S3
on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET_NAME: mclass-ins-bucket-1
  AWS_CODE_DEPLOY_APPLICATION: mclass-ins-cd-1
  AWS_CODE_DEPLOY_GROUP: mclass-ins-cd-group-1

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: touch ./src/main/resources/keyproperties/apikeys.properties
      - run: echo "${{ secrets.TRIPANT_APPLICATION }}" > ./src/main/resources/keyproperties/apikeys.properties
      - run: cat ./src/main/resources/keyproperties/apikeys.properties
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml